### ISSUE TITLE
Requires maven 3?

### ISSUE THREAD

**Issue by nealmcb** [SparkTC/systemml#5]
When I install maven2 on Ubuntu Trusty, and run

    mvn clean package

I get lots of output ending with

    Error resolving version for 'org.apache.maven.plugins:maven-shade-plugin': Plugin requires Maven version 3.0

Assuming this means that you require maven3, you should note that in the README.md, along with any other requirements (Java flavor and version? etc), and perhaps provide some hints on how to get it.  And maybe even provide some binary downloads.

**Comment by nealmcb** [comment]
I tried installing "maven" (which seems to be more up-to-date than "maven2"!): Apache Maven 3.0.5
This time I get:

`BUILD FAILURE: Failed to execute goal on project system-ml: Could not resolve dependencies for project com.ibm.systemml:system-ml:jar:5.2-SNAPSHOT: Could not find artifact jdk.tools:jdk.tools:jar:1.7 at specified path /usr/lib/jvm/java-7-openjdk-amd64/jre/../lib/tools.jar`

I assume a Java version would be helpful:

    $ java -version
    java version "1.7.0_79"
    OpenJDK Runtime Environment (IcedTea 2.5.6) (7u79-2.5.6-0ubuntu1.14.04.1)
    OpenJDK 64-Bit Server VM (build 24.79-b02, mixed mode)

**Comment by niketanpansare** [comment]
Good point nealmcb. We are planning to include installation/requirements into README soon.

Thanks for switching to maven3. To resolve the second error, please set JAVA_HOME environment variable to JDK path instead of JRE path (/usr/lib/jvm/java-7-openjdk-amd64/jre/). If you don't have JDK installed, please do "sudo apt-get install openjdk-6-jdk". Hope this helps :)

**Comment by cfregly** [comment]
@niketanpansare any chance you could move the README to the Wiki instead?  and just point to the Wiki from the README?  it makes things a lot smoother when making quick changes.  it also lets you organize into separate logical pages a lot easier.  ie. "Build Steps", "Run Steps", etc.

**Comment by nealmcb** [comment]
Thanks - that seems to work like a charm.

**Comment by deroneriksson** [comment]
@cfregly @niketanpansare The README at https://github.com/SparkTC/systemml follows the same style used by Spark at https://github.com/apache/spark, where a barebones README exists at the project root. Before moving it, I think we need to have a discussion of the benefits and drawbacks of each location.

**Comment by niketanpansare** [comment]
@cfregly @deroneriksson I would suggest let's stick to current project setup for time being and improve the content of README.

**Comment by deroneriksson** [comment]
Agreed-----Niketan Pansare <notifications@github.com> wrote: -----To: SparkTC/systemml <systemml@noreply.github.com>From: Niketan Pansare <notifications@github.com>Date: 08/31/2015 02:03PMCc: Deron Eriksson/San Francisco/IBM@IBMUSSubject: Re: [systemml] Requires maven 3? (#5)@cfregly @deroneriksson I would suggest let's stick to current project setup for time being and improve the content of README.
