### ISSUE TITLE
Specify R dependencies for mvn verify tests

### ISSUE THREAD

**Issue by nealmcb** [SparkTC/systemml#6]
When I run `mvn verify` on Ubuntu 14.04 with r-base-core, I get this test failure:

Installing packages required for running integration tests ...
Installing package into â/usr/local/lib/R/site-libraryâ
(as âlibâ is unspecified)
Warning in install.packages(pkg, repos = "http://cran.stat.ucla.edu/") :
  'lib = "/usr/local/lib/R/site-library"' is not writable
Error in install.packages(pkg, repos = "http://cran.stat.ucla.edu/") : 
  unable to install packages
....
java.lang.Exception: ERROR: R has ended irregularly
BUILD FAILURE

**Comment by niketanpansare** [comment]
Updated the README section  "Testing SystemML".

To install required packages for running integration tests, execute following command in R:

    install.packages(c("batch", "bitops", "boot", "caTools", "data.table", "doMC", "doSNOW", "ggplot2", "glmnet", "lda", "Matrix", "matrixStats", "moments", "plotrix", "psych", "reshape", "topicmodels", "wordcloud", "methods"), dependencies=TRUE) 

Known issue: package 'methods' is not available for R version 3.2.1. In which case, please downgrade R to version 3.1.1.

**Comment by deroneriksson** [comment]
@dusenberrymw @niketanpansare Mike added code to AutomatedTestBase that references the required packages for R 3.2 so that no packages should need to be installed manually.

@nealmcb That warning message looks like "/usr/local/lib/R/site-library" is not writable. Perhaps the directory (and/or parent directories) needs its permission changed to something like 755?

**Comment by niketanpansare** [comment]
@deroneriksson  Got it. Thanks. Will update the read me :) ... I am still little surprised, if AutomatedTestBase is indeed installing all the necessary packages, shouldn't "/usr/local/lib/R/site-library"  writable or not matter ? ... may be we are missing a package in AutomatedTestBase ?

**Comment by deroneriksson** [comment]
@niketanpansare I'm currently testing using R 3.1 on Mac and Mike tests with R 3.2 on Mac. Mike and Alan are also testing on Linux but not Ubuntu. I believe the 3.2 compatibility issues disappeared after Mike's addition to AutomatedTestBase on all platforms on which we're currently testing, but I don't think Ubuntu is being tested.

I'm just guessing that in the case of @nealmcb that the permissions of the site-library path need to be loosened to allow the required packages to be written/installed ("Rscript --default-packages=methods,datasets,graphics,grDevices,stats,utils"). It's quite possible it could be another issue though.

**Comment by dusenberrymw** [comment]
Ideally, we should move to using a local library path within the SystemML project directory.  This should come as part of a restructuring on the test suite.

**Comment by niketanpansare** [comment]
@deroneriksson @dusenberrymw That resolves this issue :)

@nealmcb As a workaround till restructuring of test suite is complete, please do "sudo mvn verify"

**Comment by nealmcb** [comment]
The R install.packages() command above works like a charm.  It simply has me install the extra packages in a local directory where I have write permission.

Asking people to change permissions on a system directory like `/usr/local/lib/R/site-library`, or to run tests via sudo is a very dangerous approach, and would give you a bad reputation with anyone who cares about security.
