### ISSUE TITLE
Wrong paths in README.md example

### ISSUE THREAD

**Issue by nealmcb** [SparkTC/systemml#7]
It isn't clear where and how to run the example in the README.md.

Based on the line

`./runStandaloneSystemML.sh algorithms/datagen/genLinearRegressionData.dml -nvargs numSamples=1000 numFeatures=50 maxFeatureValue=5 maxWeight=5 addNoise=FALSE b=0 sparsity=0.7 output=linRegData.csv format=csv`

I need to be in the `system-ml/scripts` directory, but that doesn't have a runStandaloneSystemML.sh.  There is a (non-executable) runStandaloneSystemML.sh in

    system-ml/src/main/standalone/runStandaloneSystemML.sh

If I set `MYSYSTEMML` to the installation directory, and run `bash $MYSYSTEMML/system-ml/src/main/standalone/runStandaloneSystemML.sh algorithms/datagen/genLinearRegressionData.dml -nvargs numSamples=1000 numFeatures=50 maxFeatureValue=5 maxWeight=5 addNoise=FALSE b=0 sparsity=0.7 output=linRegData.csv format=csv`
I get this:

    Error: Could not find or load main class com.ibm.bi.dml.api.DMLScript

My old JAVA instincts suggest I need a CLASSPATH setting that points to something near the `target` directory, but my guesses in that direction don't help.

It would seem best to actually encapsulate the whole bash script included in the README.md into an example bash script available by default which includes all the necessary path munging.

**Comment by niketanpansare** [comment]
@nealmcb  Let me give you little context here. If you look at target folder, you will see few binaries that are created. In below paragraph, I will focus on two binaries: system-ml-5.2-SNAPSHOT.jar and system-ml-5.2-SNAPSHOT-standalone.tar.gz

There are three common ways to run SystemML:
1. Using Hadoop (this requires hadoop libraries in classpath): 

    hadoop jar system-ml-5.2-SNAPSHOT.jar -f algorithms/datagen/genLinearRegressionData.dml -exec hybrid -nvargs numSamples=1000 numFeatures=50 maxFeatureValue=5 maxWeight=5 addNoise=FALSE b=0 sparsity=0.7 output=linRegData.csv format=csv

2. Using Spark (either master = local or yarn-client or yarn-cluster -> this requires yarn libraries to be in classpath): Please look at https://github.com/SparkTC/systemml/blob/master/system-ml/scripts/sparkDML.sh for details. But, here is the invocation:

    spark-submit --master local[*] system-ml-5.2-SNAPSHOT.jar -f algorithms/datagen/genLinearRegressionData.dml  -exec hybrid_spark  -nvargs ....


3. Standalone (which does not require hadoop installation): Since this has least dependency, it is presented in README. This one requires untar-ing of system-ml-5.2-SNAPSHOT-standalone.tar.gz. After untar-ing, you will see three folders along with "runStandaloneSystemML.sh": algorithms, lib and docs. The lib/ folder will contain "system-ml-5.2-SNAPSHOT.jar" along with bunch of jars which is invoked by script "runStandaloneSystemML.sh". This script internally invokes 

    java -Xmx4g -Xms4g -Xmn400m -jar system-ml-5.2-SNAPSHOT.jar -f algorithms/datagen/genLinearRegressionData.dml -exec singlenode -nvargs ....

So, to answer your question, you have to go into this un-tar folder (which will most likely be "target\system-ml-5.2-SNAPSHOT-standalone").  

We will update our README to include this information soon.

Please reply back if you have more questions :)

**Comment by nealmcb** [comment]
Thanks for the tips.  I got it to work.

But the command `target/runStandaloneSystemML.sh` from `target/system-ml-5.2-SNAPSHOT-standalone.tar.gz` really should be smart enough to find the jar files and make the CLASSPATH without being run in the target directory.  Otherwise it is a pain to keep the user data separate from SystemML itself.

The example dml scripts and data should be included with the code base (as I too-quickly assumed they were, based on the file names being used in the README.ml), along with the bash script itself as indicated earlier.   That makes the example much easier to run, avoiding the hassles of copy-paste and figuring out where to put stuff.

**Comment by niketanpansare** [comment]
@nealmcb  I think we might not be on same page. You don't have to alter your CLASSPATH. The exact steps for running the steps in README after building systemml are:

    cd into target/ (not into system-ml/src/main/standalone/)
    Untar standalone jar
    Create genLinearRegressionData.dml  
    ./runStandaloneSystemML.sh algorithms/datagen/genLinearRegressionData.dml -nvargs numSamples=1000 numFeatures=50 maxFeatureValue=5 maxWeight=5 addNoise=FALSE b=0 sparsity=0.7 output=linRegData.csv format=csv
    Create perc.csv and perc.csv.mtd
    ./runStandaloneSystemML.sh algorithms/utils/sample.dml -nvargs X=linRegData.csv sv=perc.csv O=linRegDataParts ofmt=csv
    ./runStandaloneSystemML.sh algorithms/utils/splitXY.dml -nvargs X=linRegDataParts/1 y=51 OX=linRegData.train.data.csv OY=linRegData.train.labels.csv ofmt=csv
    ./runStandaloneSystemML.sh algorithms/utils/splitXY.dml -nvargs X=linRegDataParts/2 y=51 OX=linRegData.test.data.csv OY=linRegData.test.labels.csv ofmt=csv
    ./runStandaloneSystemML.sh algorithms/LinearRegDS.dml -nvargs X=linRegData.train.data.csv Y=linRegData.train.labels.csv B=betas.csv fmt=csv
    ./runStandaloneSystemML.sh algorithms/GLM-predict.dml -nvargs X=linRegData.test.data.csv Y=linRegData.test.labels.csv B=betas.csv fmt=csv

Can you please try above step, by reseting your CLASSPATH to original one ?

**Comment by nealmcb** [comment]
That's pretty much what I did, except I put my dml scripts, including my copy of `genLinearRegressionData.dml`, in my own user directory.   I think it's important to separate my code from the SystemML.  Microsoft proved to the world decades ago what a pain it is when people end up with their own spreadsheets in the middle of the Excel product directory, a place where they shouldn't even have permissions to change things.

So I'm just pointing out that the `target/runStandaloneSystemML` command modifies the CLASSPATH by looking in the current directory:

    for f in ./lib/*.jar; do ......

That leads to an irksome requirement of running it in the target directory. It should instead be possible to run that command from a user's data or scripts directory, so it should either figure out where it is, or use an environment variable ala $SYSTEMML_HOME to get the right libraries.

**Comment by niketanpansare** [comment]
@nealmcb  The commit https://github.com/SparkTC/systemml/commit/ab6ea8b9a010c0f39bcd0b0d8f3b2f5a4e4ae0a1 should fix the current directory issue. 

I completely understand your concern. Standalone jar is a special case which requires unpacking and introduces issues that you pointed. I also agree with you, in that particular case, adding an environment variable (i.e. $SYSTEMML_HOME) make sense. However, we do not anticipate it to be our primary use-case. This is one of the reason why we have not yet decided to go into that approach. This is likely to change in future, not for standalone case but for algorithms/version management :)

**Comment by niketanpansare** [comment]
@nealmcb Sorry, I didn't address your CLASSPATH comment. Since we are explicitly using "-cp" option, we can safely replace the variable CLASSPATH with another name. This will be fixed soon (along with runStandaloneSystemML.bat which has similar problem that you mentioned).
